// Copyright 2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


export function findStarship(id: string): Starship | undefined {
	let resp = undefined;
    starships.forEach(starship => {
        if (id === starship.starshipId) {
            resp = starship;
        }
    })
    return resp;
}

export type Starship = {
	starshipId:           string
	name:                 string
	model:                string
	manufacturer:         string
	costInCredits:        number
	length:               number
	maxAtmospheringSpeed: number
	crew:                 number
	passengers:           number
	cargoCapacity:        number
	consumables:          string
	hyperdriveRating:     number
	mglt:                 number
	starshipClass:        string
	// Relationships
	pilotIds: string[]
	filmIds:  string[]
}

const starships: Starship[] = [
	{
		starshipId:           "2",
		name:                 "CR90 corvette",
		model:                "CR90 corvette",
		manufacturer:         "Corellian Engineering Corporation",
		costInCredits:        3500000,
		length:               150,
		maxAtmospheringSpeed: 950,
		crew:                 30,
		passengers:           600,
		cargoCapacity:        3000000,
		consumables:          "1 year",
		hyperdriveRating:     2,
		mglt:                 60,
		starshipClass:        "corvette",
		filmIds:              ["1", "3", "6"],
		pilotIds:             [],
    },
	{
		starshipId:           "3",
		name:                 "Star Destroyer",
		model:                "Imperial I-class Star Destroyer",
		manufacturer:         "Kuat Drive Yards",
		costInCredits:        150000000,
		length:               1600,
		maxAtmospheringSpeed: 975,
		crew:                 47060,
		passengers:           0,
		cargoCapacity:        36000000,
		consumables:          "2 years",
		hyperdriveRating:     2,
		mglt:                 60,
		starshipClass:        "Star Destroyer",
		filmIds:              ["1", "2", "3"],
		pilotIds:             [],
    },
	{
		starshipId:           "5",
		name:                 "Sentinel-class landing craft",
		model:                "Sentinel-class landing craft",
		manufacturer:         "Sienar Fleet Systems, Cyngus Spaceworks",
		costInCredits:        240000,
		length:               38,
		maxAtmospheringSpeed: 1000,
		crew:                 5,
		passengers:           75,
		cargoCapacity:        180000,
		consumables:          "1 month",
		hyperdriveRating:     1,
		mglt:                 70,
		starshipClass:        "landing craft",
		filmIds:              ["1"],
		pilotIds:             [],
    },
	{
		starshipId:           "9",
		name:                 "Death Star",
		model:                "DS-1 Orbital Battle Station",
		manufacturer:         "Imperial Department of Military Research, Sienar Fleet Systems",
		costInCredits:        1000000000000,
		length:               120000,
		maxAtmospheringSpeed: 0,
		crew:                 342953,
		passengers:           843342,
		cargoCapacity:        1000000000000,
		consumables:          "3 years",
		hyperdriveRating:     4,
		mglt:                 10,
		starshipClass:        "Deep Space Mobile Battlestation",
		filmIds:              ["1"],
		pilotIds:             [],
    },
	{
		starshipId:           "10",
		name:                 "Millennium Falcon",
		model:                "YT-1300 light freighter",
		manufacturer:         "Corellian Engineering Corporation",
		costInCredits:        100000,
		length:               34,
		maxAtmospheringSpeed: 1050,
		crew:                 4,
		passengers:           6,
		cargoCapacity:        100000,
		consumables:          "2 months",
		hyperdriveRating:     0.5,
		mglt:                 75,
		starshipClass:        "Light freighter",
		filmIds:              ["1", "2", "3"],
		pilotIds:             ["13", "14", "25", "31"],
    },
	{
		starshipId:           "11",
		name:                 "Y-wing",
		model:                "BTL Y-wing",
		manufacturer:         "Koensayr Manufacturing",
		costInCredits:        134999,
		length:               14,
		maxAtmospheringSpeed: 1000,
		crew:                 2,
		passengers:           0,
		cargoCapacity:        110,
		consumables:          "1 week",
		hyperdriveRating:     1,
		mglt:                 80,
		starshipClass:        "assault starfighter",
		filmIds:              ["1", "2", "3"],
		pilotIds:             [],
    },
	{
		starshipId:           "12",
		name:                 "X-wing",
		model:                "T-65 X-wing",
		manufacturer:         "Incom Corporation",
		costInCredits:        149999,
		length:               12,
		maxAtmospheringSpeed: 1050,
		crew:                 1,
		passengers:           0,
		cargoCapacity:        110,
		consumables:          "1 week",
		hyperdriveRating:     1,
		mglt:                 100,
		starshipClass:        "Starfighter",
		filmIds:              ["1", "2", "3"],
		pilotIds:             ["1", "9", "18", "19"],
    },
	{
		starshipId:           "13",
		name:                 "TIE Advanced x1",
		model:                "Twin Ion Engine Advanced x1",
		manufacturer:         "Sienar Fleet Systems",
		costInCredits:        0,
		length:               9,
		maxAtmospheringSpeed: 1200,
		crew:                 1,
		passengers:           0,
		cargoCapacity:        150,
		consumables:          "5 days",
		hyperdriveRating:     1,
		mglt:                 105,
		starshipClass:        "Starfighter",
		filmIds:              ["1"],
		pilotIds:             ["4"],
    },
	{
		starshipId:           "15",
		name:                 "Executor",
		model:                "Executor-class star dreadnought",
		manufacturer:         "Kuat Drive Yards, Fondor Shipyards",
		costInCredits:        1143350000,
		length:               19000,
		maxAtmospheringSpeed: 0,
		crew:                 279144,
		passengers:           38000,
		cargoCapacity:        250000000,
		consumables:          "6 years",
		hyperdriveRating:     2,
		mglt:                 40,
		starshipClass:        "Star dreadnought",
		filmIds:              ["2", "3"],
		pilotIds:             [],
    },
	{
		starshipId:           "17",
		name:                 "Rebel transport",
		model:                "GR-75 medium transport",
		manufacturer:         "Gallofree Yards, Inc.",
		costInCredits:        0,
		length:               90,
		maxAtmospheringSpeed: 650,
		crew:                 6,
		passengers:           90,
		cargoCapacity:        19000000,
		consumables:          "6 months",
		hyperdriveRating:     4,
		mglt:                 20,
		starshipClass:        "Medium transport",
		filmIds:              ["2", "3"],
		pilotIds:             [],
    },
	{
		starshipId:           "21",
		name:                 "Slave 1",
		model:                "Firespray-31-class patrol and attack",
		manufacturer:         "Kuat Systems Engineering",
		costInCredits:        0,
		length:               21,
		maxAtmospheringSpeed: 1000,
		crew:                 1,
		passengers:           6,
		cargoCapacity:        70000,
		consumables:          "1 month",
		hyperdriveRating:     3,
		mglt:                 70,
		starshipClass:        "Patrol craft",
		filmIds:              ["2", "5"],
		pilotIds:             ["22"],
    },
	{
		starshipId:           "22",
		name:                 "Imperial shuttle",
		model:                "Lambda-class T-4a shuttle",
		manufacturer:         "Sienar Fleet Systems",
		costInCredits:        240000,
		length:               20,
		maxAtmospheringSpeed: 850,
		crew:                 6,
		passengers:           20,
		cargoCapacity:        80000,
		consumables:          "2 months",
		hyperdriveRating:     1,
		mglt:                 50,
		starshipClass:        "Armed government transport",
		filmIds:              ["2", "3"],
		pilotIds:             ["1", "13", "14"],
    },
	{
		starshipId:           "23",
		name:                 "EF76 Nebulon-B escort frigate",
		model:                "EF76 Nebulon-B escort frigate",
		manufacturer:         "Kuat Drive Yards",
		costInCredits:        8500000,
		length:               300,
		maxAtmospheringSpeed: 800,
		crew:                 854,
		passengers:           75,
		cargoCapacity:        6000000,
		consumables:          "2 years",
		hyperdriveRating:     2,
		mglt:                 40,
		starshipClass:        "Escort ship",
		filmIds:              ["2", "3"],
		pilotIds:             [],
    },
	{
		starshipId:           "27",
		name:                 "Calamari Cruiser",
		model:                "MC80 Liberty type Star Cruiser",
		manufacturer:         "Mon Calamari shipyards",
		costInCredits:        104000000,
		length:               1200,
		maxAtmospheringSpeed: 0,
		crew:                 5400,
		passengers:           1200,
		cargoCapacity:        0,
		consumables:          "2 years",
		hyperdriveRating:     1,
		mglt:                 60,
		starshipClass:        "Star Cruiser",
		filmIds:              ["3"],
		pilotIds:             [],
    },
	{
		starshipId:           "28",
		name:                 "A-wing",
		model:                "RZ-1 A-wing Interceptor",
		manufacturer:         "Alliance Underground Engineering, Incom Corporation",
		costInCredits:        175000,
		length:               9,
		maxAtmospheringSpeed: 1300,
		crew:                 1,
		passengers:           0,
		cargoCapacity:        40,
		consumables:          "1 week",
		hyperdriveRating:     1,
		mglt:                 120,
		starshipClass:        "Starfighter",
		filmIds:              ["3"],
		pilotIds:             ["29"],
    },
	{
		starshipId:           "29",
		name:                 "B-wing",
		model:                "A/SF-01 B-wing starfighter",
		manufacturer:         "Slayn & Korpil",
		costInCredits:        220000,
		length:               16,
		maxAtmospheringSpeed: 950,
		crew:                 1,
		passengers:           0,
		cargoCapacity:        45,
		consumables:          "1 week",
		hyperdriveRating:     2,
		mglt:                 91,
		starshipClass:        "Assault Starfighter",
		filmIds:              ["3"],
		pilotIds:             [],
    },
	{
		starshipId:           "31",
		name:                 "Republic Cruiser",
		model:                "Consular-class cruiser",
		manufacturer:         "Corellian Engineering Corporation",
		costInCredits:        0,
		length:               115,
		maxAtmospheringSpeed: 900,
		crew:                 9,
		passengers:           16,
		cargoCapacity:        0,
		consumables:          "unknown",
		hyperdriveRating:     2,
		mglt:                 0,
		starshipClass:        "Space cruiser",
		filmIds:              ["4"],
		pilotIds:             [],
    },
	{
		starshipId:           "32",
		name:                 "Droid control ship",
		model:                "Lucrehulk-class Droid Control Ship",
		manufacturer:         "Hoersch-Kessel Drive, Inc.",
		costInCredits:        0,
		length:               3170,
		maxAtmospheringSpeed: 0,
		crew:                 175,
		passengers:           139000,
		cargoCapacity:        4000000000,
		consumables:          "500 days",
		hyperdriveRating:     2,
		mglt:                 0,
		starshipClass:        "Droid control ship",
		filmIds:              ["4", "5", "6"],
		pilotIds:             [],
    },
	{
		starshipId:           "39",
		name:                 "Naboo fighter",
		model:                "N-1 starfighter",
		manufacturer:         "Theed Palace Space Vessel Engineering Corps",
		costInCredits:        200000,
		length:               11,
		maxAtmospheringSpeed: 1100,
		crew:                 1,
		passengers:           0,
		cargoCapacity:        65,
		consumables:          "7 days",
		hyperdriveRating:     1,
		mglt:                 0,
		starshipClass:        "Starfighter",
		filmIds:              ["4", "5"],
		pilotIds:             ["11", "35", "60"],
    },
	{
		starshipId:           "40",
		name:                 "Naboo Royal Starship",
		model:                "J-type 327 Nubian royal starship",
		manufacturer:         "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives",
		costInCredits:        0,
		length:               76,
		maxAtmospheringSpeed: 920,
		crew:                 8,
		passengers:           0,
		cargoCapacity:        0,
		consumables:          "unknown",
		hyperdriveRating:     1.8,
		mglt:                 0,
		starshipClass:        "yacht",
		filmIds:              ["4"],
		pilotIds:             ["39"],
    },
	{
		starshipId:           "41",
		name:                 "Scimitar",
		model:                "Star Courier",
		manufacturer:         "Republic Sienar Systems",
		costInCredits:        55000000,
		length:               26,
		maxAtmospheringSpeed: 1180,
		crew:                 1,
		passengers:           6,
		cargoCapacity:        2500000,
		consumables:          "30 days",
		hyperdriveRating:     1.5,
		mglt:                 0,
		starshipClass:        "Space Transport",
		filmIds:              ["4"],
		pilotIds:             ["44"],
    },
	{
		starshipId:           "43",
		name:                 "J-type diplomatic barge",
		model:                "J-type diplomatic barge",
		manufacturer:         "Theed Palace Space Vessel Engineering Corps, Nubia Star Drives",
		costInCredits:        2000000,
		length:               39,
		maxAtmospheringSpeed: 2000,
		crew:                 5,
		passengers:           10,
		cargoCapacity:        0,
		consumables:          "1 year",
		hyperdriveRating:     0.7,
		mglt:                 0,
		starshipClass:        "Diplomatic barge",
		filmIds:              ["5"],
		pilotIds:             [],
    },
	{
		starshipId:           "47",
		name:                 "AA-9 Coruscant freighter",
		model:                "Botajef AA-9 Freighter-Liner",
		manufacturer:         "Botajef Shipyards",
		costInCredits:        0,
		length:               390,
		maxAtmospheringSpeed: 0,
		crew:                 0,
		passengers:           30000,
		cargoCapacity:        0,
		consumables:          "unknown",
		hyperdriveRating:     0,
		mglt:                 0,
		starshipClass:        "freighter",
		filmIds:              ["5"],
		pilotIds:             [],
    },
	{
		starshipId:           "48",
		name:                 "Jedi starfighter",
		model:                "Delta-7 Aethersprite-class interceptor",
		manufacturer:         "Kuat Systems Engineering",
		costInCredits:        180000,
		length:               8,
		maxAtmospheringSpeed: 1150,
		crew:                 1,
		passengers:           0,
		cargoCapacity:        60,
		consumables:          "7 days",
		hyperdriveRating:     1,
		mglt:                 0,
		starshipClass:        "Starfighter",
		filmIds:              ["5", "6"],
		pilotIds:             ["10", "58"],
    },
	{
		starshipId:           "49",
		name:                 "H-type Nubian yacht",
		model:                "H-type Nubian yacht",
		manufacturer:         "Theed Palace Space Vessel Engineering Corps",
		costInCredits:        0,
		length:               47,
		maxAtmospheringSpeed: 8000,
		crew:                 4,
		passengers:           0,
		cargoCapacity:        0,
		consumables:          "unknown",
		hyperdriveRating:     0.9,
		mglt:                 0,
		starshipClass:        "yacht",
		filmIds:              ["5"],
		pilotIds:             ["35"],
    },
	{
		starshipId:           "52",
		name:                 "Republic Assault ship",
		model:                "Acclamator I-class assault ship",
		manufacturer:         "Rothana Heavy Engineering",
		costInCredits:        0,
		length:               752,
		maxAtmospheringSpeed: 0,
		crew:                 700,
		passengers:           16000,
		cargoCapacity:        11250000,
		consumables:          "2 years",
		hyperdriveRating:     0.6,
		mglt:                 0,
		starshipClass:        "assault ship",
		filmIds:              ["5"],
		pilotIds:             [],
    },
	{
		starshipId:           "58",
		name:                 "Solar Sailer",
		model:                "Punworcca 116-class interstellar sloop",
		manufacturer:         "Huppla Pasa Tisc Shipwrights Collective",
		costInCredits:        35700,
		length:               15,
		maxAtmospheringSpeed: 1600,
		crew:                 3,
		passengers:           11,
		cargoCapacity:        240,
		consumables:          "7 days",
		hyperdriveRating:     1.5,
		mglt:                 0,
		starshipClass:        "yacht",
		filmIds:              ["5"],
		pilotIds:             [],
    },
	{
		starshipId:           "59",
		name:                 "Trade Federation cruiser",
		model:                "Providence-class carrier/destroyer",
		manufacturer:         "Rendili StarDrive, Free Dac Volunteers Engineering corps.",
		costInCredits:        125000000,
		length:               1088,
		maxAtmospheringSpeed: 1050,
		crew:                 600,
		passengers:           48247,
		cargoCapacity:        50000000,
		consumables:          "4 years",
		hyperdriveRating:     1.5,
		mglt:                 0,
		starshipClass:        "capital ship",
		filmIds:              ["6"],
		pilotIds:             ["10", "11"],
    },
	{
		starshipId:           "61",
		name:                 "Theta-class T-2c shuttle",
		model:                "Theta-class T-2c shuttle",
		manufacturer:         "Cygnus Spaceworks",
		costInCredits:        1000000,
		length:               18,
		maxAtmospheringSpeed: 2000,
		crew:                 5,
		passengers:           16,
		cargoCapacity:        50000,
		consumables:          "56 days",
		hyperdriveRating:     1,
		mglt:                 0,
		starshipClass:        "transport",
		filmIds:              ["6"],
		pilotIds:             [],
    },
	{
		starshipId:           "63",
		name:                 "Republic attack cruiser",
		model:                "Senator-class Star Destroyer",
		manufacturer:         "Kuat Drive Yards, Allanteen Six shipyards",
		costInCredits:        59000000,
		length:               1137,
		maxAtmospheringSpeed: 975,
		crew:                 7400,
		passengers:           2000,
		cargoCapacity:        20000000,
		consumables:          "2 years",
		hyperdriveRating:     1,
		mglt:                 0,
		starshipClass:        "star destroyer",
		filmIds:              ["6"],
		pilotIds:             [],
    },
	{
		starshipId:           "64",
		name:                 "Naboo star skiff",
		model:                "J-type star skiff",
		manufacturer:         "Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated",
		costInCredits:        0,
		length:               29,
		maxAtmospheringSpeed: 1050,
		crew:                 3,
		passengers:           3,
		cargoCapacity:        0,
		consumables:          "unknown",
		hyperdriveRating:     0.5,
		mglt:                 0,
		starshipClass:        "yacht",
		filmIds:              ["6"],
		pilotIds:             ["10", "35"],
    },
	{
		starshipId:           "65",
		name:                 "Jedi Interceptor",
		model:                "Eta-2 Actis-class light interceptor",
		manufacturer:         "Kuat Systems Engineering",
		costInCredits:        320000,
		length:               5,
		maxAtmospheringSpeed: 1500,
		crew:                 1,
		passengers:           0,
		cargoCapacity:        60,
		consumables:          "2 days",
		hyperdriveRating:     1,
		mglt:                 0,
		starshipClass:        "starfighter",
		filmIds:              ["6"],
		pilotIds:             ["10", "11"],
    },
	{
		starshipId:           "66",
		name:                 "arc-170",
		model:                "Aggressive Reconnaissance-170 starfighte",
		manufacturer:         "Incom Corporation, Subpro Corporation",
		costInCredits:        155000,
		length:               14,
		maxAtmospheringSpeed: 1000,
		crew:                 3,
		passengers:           0,
		cargoCapacity:        110,
		consumables:          "5 days",
		hyperdriveRating:     1,
		mglt:                 100,
		starshipClass:        "starfighter",
		filmIds:              ["6"],
		pilotIds:             [],
    },
	{
		starshipId:           "68",
		name:                 "Banking clan frigte",
		model:                "Munificent-class star frigate",
		manufacturer:         "Hoersch-Kessel Drive, Inc, Gwori Revolutionary Industries",
		costInCredits:        57000000,
		length:               825,
		maxAtmospheringSpeed: 0,
		crew:                 200,
		passengers:           0,
		cargoCapacity:        40000000,
		consumables:          "2 years",
		hyperdriveRating:     1,
		mglt:                 0,
		starshipClass:        "cruiser",
		filmIds:              ["6"],
		pilotIds:             [],
    },
	{
		starshipId:           "74",
		name:                 "Belbullab-22 starfighter",
		model:                "Belbullab-22 starfighter",
		manufacturer:         "Feethan Ottraw Scalable Assemblies",
		costInCredits:        168000,
		length:               6,
		maxAtmospheringSpeed: 1100,
		crew:                 1,
		passengers:           0,
		cargoCapacity:        140,
		consumables:          "7 days",
		hyperdriveRating:     6,
		mglt:                 0,
		starshipClass:        "starfighter",
		filmIds:              ["6"],
		pilotIds:             ["10", "79"],
    },
	{
		starshipId:           "75",
		name:                 "V-wing",
		model:                "Alpha-3 Nimbus-class V-wing starfighter",
		manufacturer:         "Kuat Systems Engineering",
		costInCredits:        102500,
		length:               7,
		maxAtmospheringSpeed: 1050,
		crew:                 1,
		passengers:           0,
		cargoCapacity:        60,
		consumables:          "15 hours",
		hyperdriveRating:     1,
		mglt:                 0,
		starshipClass:        "starfighter",
		filmIds:              ["6"],
		pilotIds:             [],
    },
]
