// Copyright 2023 Buf Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package person

// Find person with given id.
func Find(id string) *Person {
	for _, v := range people {
		if v.PersonID == id {
			other := v
			return &other
		}
	}
	return nil
}

type Person struct {
	PersonID  string
	Name      string
	Height    uint64
	Mass      uint64
	BirthYear string
	Gender    string
	Homeworld string
	// Relationships
	FilmIDs     []string
	StarshipIDs []string
	VehicleIDs  []string
	SpeciesIDs  []string
}

var people = []Person{
	{
		PersonID:    "1",
		Name:        "Luke Skywalker",
		Height:      172,
		Mass:        77,
		BirthYear:   "19BBY",
		Gender:      "male",
		Homeworld:   "1",
		FilmIDs:     []string{"1", "2", "3", "6"},
		StarshipIDs: []string{"12", "22"},
		VehicleIDs:  []string{"14", "30"},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "2",
		Name:        "C-3PO",
		Height:      167,
		Mass:        75,
		BirthYear:   "112BBY",
		Gender:      "n/a",
		Homeworld:   "1",
		FilmIDs:     []string{"1", "2", "3", "4", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"2"},
	},
	{
		PersonID:    "3",
		Name:        "R2-D2",
		Height:      96,
		Mass:        32,
		BirthYear:   "33BBY",
		Gender:      "n/a",
		Homeworld:   "8",
		FilmIDs:     []string{"1", "2", "3", "4", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"2"},
	},
	{
		PersonID:    "4",
		Name:        "Darth Vader",
		Height:      202,
		Mass:        136,
		BirthYear:   "41.9BBY",
		Gender:      "male",
		Homeworld:   "1",
		FilmIDs:     []string{"1", "2", "3", "6"},
		StarshipIDs: []string{"13"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "5",
		Name:        "Leia Organa",
		Height:      150,
		Mass:        49,
		BirthYear:   "19BBY",
		Gender:      "female",
		Homeworld:   "2",
		FilmIDs:     []string{"1", "2", "3", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{"30"},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "6",
		Name:        "Owen Lars",
		Height:      178,
		Mass:        120,
		BirthYear:   "52BBY",
		Gender:      "male",
		Homeworld:   "1",
		FilmIDs:     []string{"1", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "7",
		Name:        "Beru Whitesun lars",
		Height:      165,
		Mass:        75,
		BirthYear:   "47BBY",
		Gender:      "female",
		Homeworld:   "1",
		FilmIDs:     []string{"1", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "8",
		Name:        "R5-D4",
		Height:      97,
		Mass:        32,
		BirthYear:   "unknown",
		Gender:      "n/a",
		Homeworld:   "1",
		FilmIDs:     []string{"1"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"2"},
	},
	{
		PersonID:    "9",
		Name:        "Biggs Darklighter",
		Height:      183,
		Mass:        84,
		BirthYear:   "24BBY",
		Gender:      "male",
		Homeworld:   "1",
		FilmIDs:     []string{"1"},
		StarshipIDs: []string{"12"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "10",
		Name:        "Obi-Wan Kenobi",
		Height:      182,
		Mass:        77,
		BirthYear:   "57BBY",
		Gender:      "male",
		Homeworld:   "20",
		FilmIDs:     []string{"1", "2", "3", "4", "5", "6"},
		StarshipIDs: []string{"48", "59", "64", "65", "74"},
		VehicleIDs:  []string{"38"},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "11",
		Name:        "Anakin Skywalker",
		Height:      188,
		Mass:        84,
		BirthYear:   "41.9BBY",
		Gender:      "male",
		Homeworld:   "1",
		FilmIDs:     []string{"4", "5", "6"},
		StarshipIDs: []string{"39", "59", "65"},
		VehicleIDs:  []string{"44", "46"},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "12",
		Name:        "Wilhuff Tarkin",
		Height:      180,
		Mass:        0,
		BirthYear:   "64BBY",
		Gender:      "male",
		Homeworld:   "21",
		FilmIDs:     []string{"1", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "13",
		Name:        "Chewbacca",
		Height:      228,
		Mass:        112,
		BirthYear:   "200BBY",
		Gender:      "male",
		Homeworld:   "14",
		FilmIDs:     []string{"1", "2", "3", "6"},
		StarshipIDs: []string{"10", "22"},
		VehicleIDs:  []string{"19"},
		SpeciesIDs:  []string{"3"},
	},
	{
		PersonID:    "14",
		Name:        "Han Solo",
		Height:      180,
		Mass:        80,
		BirthYear:   "29BBY",
		Gender:      "male",
		Homeworld:   "22",
		FilmIDs:     []string{"1", "2", "3"},
		StarshipIDs: []string{"10", "22"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "15",
		Name:        "Greedo",
		Height:      173,
		Mass:        74,
		BirthYear:   "44BBY",
		Gender:      "male",
		Homeworld:   "23",
		FilmIDs:     []string{"1"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"4"},
	},
	{
		PersonID:    "16",
		Name:        "Jabba Desilijic Tiure",
		Height:      175,
		Mass:        1358,
		BirthYear:   "600BBY",
		Gender:      "hermaphrodite",
		Homeworld:   "24",
		FilmIDs:     []string{"1", "3", "4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"5"},
	},
	{
		PersonID:    "18",
		Name:        "Wedge Antilles",
		Height:      170,
		Mass:        77,
		BirthYear:   "21BBY",
		Gender:      "male",
		Homeworld:   "22",
		FilmIDs:     []string{"1", "2", "3"},
		StarshipIDs: []string{"12"},
		VehicleIDs:  []string{"14"},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "19",
		Name:        "Jek Tono Porkins",
		Height:      180,
		Mass:        110,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "26",
		FilmIDs:     []string{"1"},
		StarshipIDs: []string{"12"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "20",
		Name:        "Yoda",
		Height:      66,
		Mass:        17,
		BirthYear:   "896BBY",
		Gender:      "male",
		Homeworld:   "28",
		FilmIDs:     []string{"2", "3", "4", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"6"},
	},
	{
		PersonID:    "21",
		Name:        "Palpatine",
		Height:      170,
		Mass:        75,
		BirthYear:   "82BBY",
		Gender:      "male",
		Homeworld:   "8",
		FilmIDs:     []string{"2", "3", "4", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "22",
		Name:        "Boba Fett",
		Height:      183,
		Mass:        78,
		BirthYear:   "31.5BBY",
		Gender:      "male",
		Homeworld:   "10",
		FilmIDs:     []string{"2", "3", "5"},
		StarshipIDs: []string{"21"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "23",
		Name:        "IG-88",
		Height:      200,
		Mass:        140,
		BirthYear:   "15BBY",
		Gender:      "none",
		Homeworld:   "28",
		FilmIDs:     []string{"2"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"2"},
	},
	{
		PersonID:    "24",
		Name:        "Bossk",
		Height:      190,
		Mass:        113,
		BirthYear:   "53BBY",
		Gender:      "male",
		Homeworld:   "29",
		FilmIDs:     []string{"2"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"7"},
	},
	{
		PersonID:    "25",
		Name:        "Lando Calrissian",
		Height:      177,
		Mass:        79,
		BirthYear:   "31BBY",
		Gender:      "male",
		Homeworld:   "30",
		FilmIDs:     []string{"2", "3"},
		StarshipIDs: []string{"10"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "26",
		Name:        "Lobot",
		Height:      175,
		Mass:        79,
		BirthYear:   "37BBY",
		Gender:      "male",
		Homeworld:   "6",
		FilmIDs:     []string{"2"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "27",
		Name:        "Ackbar",
		Height:      180,
		Mass:        83,
		BirthYear:   "41BBY",
		Gender:      "male",
		Homeworld:   "31",
		FilmIDs:     []string{"3"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"8"},
	},
	{
		PersonID:    "28",
		Name:        "Mon Mothma",
		Height:      150,
		Mass:        0,
		BirthYear:   "48BBY",
		Gender:      "female",
		Homeworld:   "32",
		FilmIDs:     []string{"3"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "29",
		Name:        "Arvel Crynyd",
		Height:      0,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "28",
		FilmIDs:     []string{"3"},
		StarshipIDs: []string{"28"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "30",
		Name:        "Wicket Systri Warrick",
		Height:      88,
		Mass:        20,
		BirthYear:   "8BBY",
		Gender:      "male",
		Homeworld:   "7",
		FilmIDs:     []string{"3"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"9"},
	},
	{
		PersonID:    "31",
		Name:        "Nien Nunb",
		Height:      160,
		Mass:        68,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "33",
		FilmIDs:     []string{"3"},
		StarshipIDs: []string{"10"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"10"},
	},
	{
		PersonID:    "32",
		Name:        "Qui-Gon Jinn",
		Height:      193,
		Mass:        89,
		BirthYear:   "92BBY",
		Gender:      "male",
		Homeworld:   "28",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{"38"},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "33",
		Name:        "Nute Gunray",
		Height:      191,
		Mass:        90,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "18",
		FilmIDs:     []string{"4", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"11"},
	},
	{
		PersonID:    "34",
		Name:        "Finis Valorum",
		Height:      170,
		Mass:        0,
		BirthYear:   "91BBY",
		Gender:      "male",
		Homeworld:   "9",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "35",
		Name:        "Padmé Amidala",
		Height:      185,
		Mass:        45,
		BirthYear:   "46BBY",
		Gender:      "female",
		Homeworld:   "8",
		FilmIDs:     []string{"4", "5", "6"},
		StarshipIDs: []string{"39", "49", "64"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "36",
		Name:        "Jar Jar Binks",
		Height:      196,
		Mass:        66,
		BirthYear:   "52BBY",
		Gender:      "male",
		Homeworld:   "8",
		FilmIDs:     []string{"4", "5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"12"},
	},
	{
		PersonID:    "37",
		Name:        "Roos Tarpals",
		Height:      224,
		Mass:        82,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "8",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"12"},
	},
	{
		PersonID:    "38",
		Name:        "Rugor Nass",
		Height:      206,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "8",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"12"},
	},
	{
		PersonID:    "39",
		Name:        "Ric Olié",
		Height:      183,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "8",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{"40"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "40",
		Name:        "Watto",
		Height:      137,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "34",
		FilmIDs:     []string{"4", "5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"13"},
	},
	{
		PersonID:    "41",
		Name:        "Sebulba",
		Height:      112,
		Mass:        40,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "35",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"14"},
	},
	{
		PersonID:    "42",
		Name:        "Quarsh Panaka",
		Height:      183,
		Mass:        0,
		BirthYear:   "62BBY",
		Gender:      "male",
		Homeworld:   "8",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "43",
		Name:        "Shmi Skywalker",
		Height:      163,
		Mass:        0,
		BirthYear:   "72BBY",
		Gender:      "female",
		Homeworld:   "1",
		FilmIDs:     []string{"4", "5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "44",
		Name:        "Darth Maul",
		Height:      175,
		Mass:        80,
		BirthYear:   "54BBY",
		Gender:      "male",
		Homeworld:   "36",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{"41"},
		VehicleIDs:  []string{"42"},
		SpeciesIDs:  []string{"22"},
	},
	{
		PersonID:    "45",
		Name:        "Bib Fortuna",
		Height:      180,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "37",
		FilmIDs:     []string{"3"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"15"},
	},
	{
		PersonID:    "46",
		Name:        "Ayla Secura",
		Height:      178,
		Mass:        55,
		BirthYear:   "48BBY",
		Gender:      "female",
		Homeworld:   "37",
		FilmIDs:     []string{"4", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"15"},
	},
	{
		PersonID:    "47",
		Name:        "Ratts Tyerel",
		Height:      79,
		Mass:        15,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "38",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"16"},
	},
	{
		PersonID:    "48",
		Name:        "Dud Bolt",
		Height:      94,
		Mass:        45,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "39",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"17"},
	},
	{
		PersonID:    "49",
		Name:        "Gasgano",
		Height:      122,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "40",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"18"},
	},
	{
		PersonID:    "50",
		Name:        "Ben Quadinaros",
		Height:      163,
		Mass:        65,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "41",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"19"},
	},
	{
		PersonID:    "51",
		Name:        "Mace Windu",
		Height:      188,
		Mass:        84,
		BirthYear:   "72BBY",
		Gender:      "male",
		Homeworld:   "42",
		FilmIDs:     []string{"4", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "52",
		Name:        "Ki-Adi-Mundi",
		Height:      198,
		Mass:        82,
		BirthYear:   "92BBY",
		Gender:      "male",
		Homeworld:   "43",
		FilmIDs:     []string{"4", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"20"},
	},
	{
		PersonID:    "53",
		Name:        "Kit Fisto",
		Height:      196,
		Mass:        87,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "44",
		FilmIDs:     []string{"4", "5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"21"},
	},
	{
		PersonID:    "54",
		Name:        "Eeth Koth",
		Height:      171,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "45",
		FilmIDs:     []string{"4", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"22"},
	},
	{
		PersonID:    "55",
		Name:        "Adi Gallia",
		Height:      184,
		Mass:        50,
		BirthYear:   "unknown",
		Gender:      "female",
		Homeworld:   "9",
		FilmIDs:     []string{"4", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"23"},
	},
	{
		PersonID:    "56",
		Name:        "Saesee Tiin",
		Height:      188,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "47",
		FilmIDs:     []string{"4", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"24"},
	},
	{
		PersonID:    "57",
		Name:        "Yarael Poof",
		Height:      264,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "48",
		FilmIDs:     []string{"4"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"25"},
	},
	{
		PersonID:    "58",
		Name:        "Plo Koon",
		Height:      188,
		Mass:        80,
		BirthYear:   "22BBY",
		Gender:      "male",
		Homeworld:   "49",
		FilmIDs:     []string{"4", "5", "6"},
		StarshipIDs: []string{"48"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"26"},
	},
	{
		PersonID:    "59",
		Name:        "Mas Amedda",
		Height:      196,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "50",
		FilmIDs:     []string{"4", "5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"27"},
	},
	{
		PersonID:    "60",
		Name:        "Gregar Typho",
		Height:      185,
		Mass:        85,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "8",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{"39"},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "61",
		Name:        "Cordé",
		Height:      157,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "female",
		Homeworld:   "8",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "62",
		Name:        "Cliegg Lars",
		Height:      183,
		Mass:        0,
		BirthYear:   "82BBY",
		Gender:      "male",
		Homeworld:   "1",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "63",
		Name:        "Poggle the Lesser",
		Height:      183,
		Mass:        80,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "11",
		FilmIDs:     []string{"5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"28"},
	},
	{
		PersonID:    "64",
		Name:        "Luminara Unduli",
		Height:      170,
		Mass:        56,
		BirthYear:   "58BBY",
		Gender:      "female",
		Homeworld:   "51",
		FilmIDs:     []string{"5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"29"},
	},
	{
		PersonID:    "65",
		Name:        "Barriss Offee",
		Height:      166,
		Mass:        50,
		BirthYear:   "40BBY",
		Gender:      "female",
		Homeworld:   "51",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"29"},
	},
	{
		PersonID:    "66",
		Name:        "Dormé",
		Height:      165,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "female",
		Homeworld:   "8",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"1"},
	},
	{
		PersonID:    "67",
		Name:        "Dooku",
		Height:      193,
		Mass:        80,
		BirthYear:   "102BBY",
		Gender:      "male",
		Homeworld:   "52",
		FilmIDs:     []string{"5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{"55"},
		SpeciesIDs:  []string{"1"},
	},
	{
		PersonID:    "68",
		Name:        "Bail Prestor Organa",
		Height:      191,
		Mass:        0,
		BirthYear:   "67BBY",
		Gender:      "male",
		Homeworld:   "2",
		FilmIDs:     []string{"5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"1"},
	},
	{
		PersonID:    "69",
		Name:        "Jango Fett",
		Height:      183,
		Mass:        79,
		BirthYear:   "66BBY",
		Gender:      "male",
		Homeworld:   "53",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "70",
		Name:        "Zam Wesell",
		Height:      168,
		Mass:        55,
		BirthYear:   "unknown",
		Gender:      "female",
		Homeworld:   "54",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{"45"},
		SpeciesIDs:  []string{"30"},
	},
	{
		PersonID:    "71",
		Name:        "Dexter Jettster",
		Height:      198,
		Mass:        102,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "55",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"31"},
	},
	{
		PersonID:    "72",
		Name:        "Lama Su",
		Height:      229,
		Mass:        88,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "10",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"32"},
	},
	{
		PersonID:    "73",
		Name:        "Taun We",
		Height:      213,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "female",
		Homeworld:   "10",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"32"},
	},
	{
		PersonID:    "74",
		Name:        "Jocasta Nu",
		Height:      167,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "female",
		Homeworld:   "9",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"1"},
	},
	{
		PersonID:    "75",
		Name:        "R4-P17",
		Height:      96,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "female",
		Homeworld:   "28",
		FilmIDs:     []string{"5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "76",
		Name:        "Wat Tambor",
		Height:      193,
		Mass:        48,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "56",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"33"},
	},
	{
		PersonID:    "77",
		Name:        "San Hill",
		Height:      191,
		Mass:        0,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "57",
		FilmIDs:     []string{"5"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"34"},
	},
	{
		PersonID:    "78",
		Name:        "Shaak Ti",
		Height:      178,
		Mass:        57,
		BirthYear:   "unknown",
		Gender:      "female",
		Homeworld:   "58",
		FilmIDs:     []string{"5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"35"},
	},
	{
		PersonID:    "79",
		Name:        "Grievous",
		Height:      216,
		Mass:        159,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "59",
		FilmIDs:     []string{"6"},
		StarshipIDs: []string{"74"},
		VehicleIDs:  []string{"60"},
		SpeciesIDs:  []string{"36"},
	},
	{
		PersonID:    "80",
		Name:        "Tarfful",
		Height:      234,
		Mass:        136,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "14",
		FilmIDs:     []string{"6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"3"},
	},
	{
		PersonID:    "81",
		Name:        "Raymus Antilles",
		Height:      188,
		Mass:        79,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "2",
		FilmIDs:     []string{"1", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "82",
		Name:        "Sly Moore",
		Height:      178,
		Mass:        48,
		BirthYear:   "unknown",
		Gender:      "female",
		Homeworld:   "60",
		FilmIDs:     []string{"5", "6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{},
	},
	{
		PersonID:    "83",
		Name:        "Tion Medon",
		Height:      206,
		Mass:        80,
		BirthYear:   "unknown",
		Gender:      "male",
		Homeworld:   "12",
		FilmIDs:     []string{"6"},
		StarshipIDs: []string{},
		VehicleIDs:  []string{},
		SpeciesIDs:  []string{"37"},
	},
}
